In [13]:
import pandas as pd
import numpy as np

In [14]:
data = pd.read_csv("otodom_scraped_data.csv")

In [15]:
data.head()

,id,title,price,currency,square footage,rooms,floor,district
0,67795620,Stylowe 2 pokoje | Grzegórzki | miejsce postoj...,1227000.0,PLN,50.18,TWO,FIRST,Prądnik Czerwony
1,67860096,Przestronna kawalerka w świetnej lokalizacji!,560000.0,PLN,36.00,ONE,SECOND,Prądnik Czerwony
2,66324565,Look UP House,NaN,NaN,NaN,NaN,NaN,Prądnik Biały
3,67860081,3 pokoje | 47 m | Do generalnego remontu,589000.0,PLN,47.00,THREE,FIRST,Bieżanów-Prokocim
4,66324017,3-pokojowe mieszkanie 73m2 + balkon Bez Prowizji,977089.0,PLN,73.89,THREE,SECOND,Podgórze

In [16]:
data_01 = data.drop('id', axis = 'columns')

In [17]:
data_01.head()

,title,price,currency,square footage,rooms,floor,district
0,Stylowe 2 pokoje | Grzegórzki | miejsce postoj...,1227000.0,PLN,50.18,TWO,FIRST,Prądnik Czerwony
1,Przestronna kawalerka w świetnej lokalizacji!,560000.0,PLN,36.00,ONE,SECOND,Prądnik Czerwony
2,Look UP House,NaN,NaN,NaN,NaN,NaN,Prądnik Biały
3,3 pokoje | 47 m | Do generalnego remontu,589000.0,PLN,47.00,THREE,FIRST,Bieżanów-Prokocim
4,3-pokojowe mieszkanie 73m2 + balkon Bez Prowizji,977089.0,PLN,73.89,THREE,SECOND,Podgórze

In [18]:
data_without_NA = data_01.dropna()

In [20]:
data_without_NA.head()

,title,price,currency,square footage,rooms,floor,district
0,Stylowe 2 pokoje | Grzegórzki | miejsce postoj...,1227000.0,PLN,50.18,TWO,FIRST,Prądnik Czerwony
1,Przestronna kawalerka w świetnej lokalizacji!,560000.0,PLN,36.00,ONE,SECOND,Prądnik Czerwony
3,3 pokoje | 47 m | Do generalnego remontu,589000.0,PLN,47.00,THREE,FIRST,Bieżanów-Prokocim
4,3-pokojowe mieszkanie 73m2 + balkon Bez Prowizji,977089.0,PLN,73.89,THREE,SECOND,Podgórze
5,Sosnowicka | Eko Park | 48 m2 | 2 pok | klima,888000.0,PLN,48.35,TWO,SECOND,Prądnik Biały

In [ ]:
room_map = {'ONE': 1, 'TWO': 2, 'THREE': 3, 'FOUR': 4, 'FIVE':5, 'SIX':6,'SEVEN': 7, 'EIGHT':8, 'NINE':9, 'TEN':10, 'NINE':9, 'TEN':10, 'MORE':11}
data_without_NA["rooms"].unique()

<StringArray>
[  'TWO',   'ONE', 'THREE',  'FOUR', 'SEVEN',  'FIVE',   'SIX', 'EIGHT',
  'MORE',   'TEN',  'NINE']
Length: 11, dtype: str