In [72]:
import pandas as pd
import numpy as np
import os 
from sklearn.impute import KNNImputer

In [73]:
DETAIL_PATH = os.path.join("raw", "details_data.csv")
GENERAL_PATH = os.path.join("raw", "general_data.csv")
details = pd.read_csv(DETAIL_PATH)
general = pd.read_csv(GENERAL_PATH)

In [74]:
details = details.drop('floor', axis = 'columns')

In [75]:
merged = general.merge(details, left_on="slug", right_on="slug")

In [76]:
merged = merged.drop_duplicates().reset_index(drop = True)

In [77]:
merged.head(2)

,slug,title,price,square footage,rooms,floor,district,market,build_year,house_type,heating,condidtion,extras,urls
0,2-pokojowe-mieszkanie-45m2-balkon-bezposrednio...,2-pokojowe mieszkanie 45m2 + balkon Bezpośrednio,702000.0,45.00,TWO,FIRST,Podgórze Duchackie,primary,2027.0,block,urban,to_completion,"balcony,garage,lift",https://ireland.apollo.olxcdn.com/v1/files/eyJ...
1,4-pokojowe-mieszkanie-75m2-ogrodek-ID4uk3x,4-pokojowe mieszkanie 75m2 + ogródek,1080432.0,75.03,FOUR,GROUND,Prądnik Czerwony,primary,2026.0,NaN,NaN,to_completion,"garage,garden,lift",https://ireland.apollo.olxcdn.com/v1/files/eyJ...

In [ ]:
merged = merged.dropna(subset=['price', 'square footage', 'rooms', 'floor'])
room_map = {'ONE': 1, 'TWO': 2, 'THREE': 3, 'FOUR': 4, 'FIVE':5, 'SIX':6,'SEVEN': 7, 'EIGHT':8, 'NINE':9, 'TEN':10, 'MORE':11}
floor_map = {'FIRST' : 1, 'SECOND' : 2, 'FIFTH': 5,'EIGHTH':8,'THIRD':3, 'FOURTH':4,'CELLAR':-1,'SIXTH' :6, 'SEVENTH':7,'TENTH':10,'NINTH' : 9,'GARRET':11, 'ABOVE_TENTH':11,'GROUND':0}
merged = pd.get_dummies(merged, columns=['district'], dtype = int)
merged['rooms'] = merged['rooms'].map(room_map)
merged['floor'] = merged['floor'].map(floor_map)

In [ ]:
# Implement KNN to fill data ;)

,slug,title,price,square footage,rooms,floor,market,build_year,house_type,heating,...,district_Prądnik Czerwony,district_Skawina,district_Stare Miasto,district_Swoszowice,district_Wieliczka,district_Wielka Wieś,district_Wzgórza Krzesławickie,district_Zielonki,district_Zwierzyniec,district_Łagiewniki-Borek Fałęcki
0,2-pokojowe-mieszkanie-45m2-balkon-bezposrednio...,2-pokojowe mieszkanie 45m2 + balkon Bezpośrednio,702000.0,45.00,NaN,NaN,primary,2027.0,block,urban,...,0,0,0,0,0,0,0,0,0,0
1,4-pokojowe-mieszkanie-75m2-ogrodek-ID4uk3x,4-pokojowe mieszkanie 75m2 + ogródek,1080432.0,75.03,NaN,NaN,primary,2026.0,NaN,NaN,...,1,0,0,0,0,0,0,0,0,0